In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("reddit_data.csv")

In [38]:
df.head()

,title,score,upvote_ratio,num_comments,created_utc,subreddit,is_self,awards,url,post_hour,post_day,is_weekend,title_words_count,has_question,has_number,controversy_index,sentiment_score,is_extreme_sentiment,viral
0,The Removed DOGE Deposition Videos Have Alread...,55179,0.97,1016,1.773538e+09,technology,0,0,https://www.404media.co/the-removed-doge-depos...,1,6,1,47,0,0,0.207738,0.0258,0,1
1,ChatGPT uninstalls surged by 295% after DoD deal,43096,0.96,1286,1.772496e+09,technology,0,0,https://techcrunch.com/2026/03/02/chatgpt-unin...,0,1,0,8,0,1,0.286403,0.0000,0,1
2,1.5 Million Users Leave ChatGPT,38902,0.96,1525,1.772563e+09,technology,0,0,https://www.forbes.com/sites/barrycollins/2026...,18,1,0,5,0,1,0.293216,-0.0516,0,1
3,‘Another internet is possible’: Norway rails a...,35918,0.97,1463,1.773662e+09,technology,0,0,https://www.theguardian.com/world/2026/mar/16/...,11,0,0,8,0,0,0.218668,0.0000,0,1
4,DOGE employee stole Social Security data and p...,35822,0.97,838,1.773174e+09,technology,0,0,https://techcrunch.com/2026/03/10/doge-employe...,20,1,0,15,0,0,0.201966,0.3400,0,1

In [4]:
print(df.shape)

(1000, 9)

In [5]:
df.columns

Index(['title', 'score', 'upvote_ratio', 'num_comments', 'created_utc',
       'subreddit', 'is_self', 'awards', 'url'],
      dtype='object')

In [6]:
df["post_hour"] = pd.to_datetime(df["created_utc"], unit="s").dt.hour

In [7]:
df.head()

,title,score,upvote_ratio,num_comments,created_utc,subreddit,is_self,awards,url,post_hour
0,The Removed DOGE Deposition Videos Have Alread...,55179,0.97,1016,1.773538e+09,technology,False,0,https://www.404media.co/the-removed-doge-depos...,1
1,ChatGPT uninstalls surged by 295% after DoD deal,43096,0.96,1286,1.772496e+09,technology,False,0,https://techcrunch.com/2026/03/02/chatgpt-unin...,0
2,1.5 Million Users Leave ChatGPT,38902,0.96,1525,1.772563e+09,technology,False,0,https://www.forbes.com/sites/barrycollins/2026...,18
3,‘Another internet is possible’: Norway rails a...,35918,0.97,1463,1.773662e+09,technology,False,0,https://www.theguardian.com/world/2026/mar/16/...,11
4,DOGE employee stole Social Security data and p...,35822,0.97,838,1.773174e+09,technology,False,0,https://techcrunch.com/2026/03/10/doge-employe...,20

In [9]:
df["post_day"] = pd.to_datetime(df["created_utc"], unit="s").dt.dayofweek

In [11]:
df.head()

,title,score,upvote_ratio,num_comments,created_utc,subreddit,is_self,awards,url,post_hour,post_day
0,The Removed DOGE Deposition Videos Have Alread...,55179,0.97,1016,1.773538e+09,technology,False,0,https://www.404media.co/the-removed-doge-depos...,1,6
1,ChatGPT uninstalls surged by 295% after DoD deal,43096,0.96,1286,1.772496e+09,technology,False,0,https://techcrunch.com/2026/03/02/chatgpt-unin...,0,1
2,1.5 Million Users Leave ChatGPT,38902,0.96,1525,1.772563e+09,technology,False,0,https://www.forbes.com/sites/barrycollins/2026...,18,1
3,‘Another internet is possible’: Norway rails a...,35918,0.97,1463,1.773662e+09,technology,False,0,https://www.theguardian.com/world/2026/mar/16/...,11,0
4,DOGE employee stole Social Security data and p...,35822,0.97,838,1.773174e+09,technology,False,0,https://techcrunch.com/2026/03/10/doge-employe...,20,1

In [12]:
df["post_day"].isin([5, 6]).astype(int)

0      1
1      0
2      0
3      0
4      0
      ..
995    0
996    0
997    1
998    0
999    0
Name: post_day, Length: 1000, dtype: int64

In [13]:
df.head()

,title,score,upvote_ratio,num_comments,created_utc,subreddit,is_self,awards,url,post_hour,post_day
0,The Removed DOGE Deposition Videos Have Alread...,55179,0.97,1016,1.773538e+09,technology,False,0,https://www.404media.co/the-removed-doge-depos...,1,6
1,ChatGPT uninstalls surged by 295% after DoD deal,43096,0.96,1286,1.772496e+09,technology,False,0,https://techcrunch.com/2026/03/02/chatgpt-unin...,0,1
2,1.5 Million Users Leave ChatGPT,38902,0.96,1525,1.772563e+09,technology,False,0,https://www.forbes.com/sites/barrycollins/2026...,18,1
3,‘Another internet is possible’: Norway rails a...,35918,0.97,1463,1.773662e+09,technology,False,0,https://www.theguardian.com/world/2026/mar/16/...,11,0
4,DOGE employee stole Social Security data and p...,35822,0.97,838,1.773174e+09,technology,False,0,https://techcrunch.com/2026/03/10/doge-employe...,20,1

In [14]:
df["is_weekend"] =  df["post_day"].isin([5, 6]).astype(int)

In [15]:
df.head()

,title,score,upvote_ratio,num_comments,created_utc,subreddit,is_self,awards,url,post_hour,post_day,is_weekend
0,The Removed DOGE Deposition Videos Have Alread...,55179,0.97,1016,1.773538e+09,technology,False,0,https://www.404media.co/the-removed-doge-depos...,1,6,1
1,ChatGPT uninstalls surged by 295% after DoD deal,43096,0.96,1286,1.772496e+09,technology,False,0,https://techcrunch.com/2026/03/02/chatgpt-unin...,0,1,0
2,1.5 Million Users Leave ChatGPT,38902,0.96,1525,1.772563e+09,technology,False,0,https://www.forbes.com/sites/barrycollins/2026...,18,1,0
3,‘Another internet is possible’: Norway rails a...,35918,0.97,1463,1.773662e+09,technology,False,0,https://www.theguardian.com/world/2026/mar/16/...,11,0,0
4,DOGE employee stole Social Security data and p...,35822,0.97,838,1.773174e+09,technology,False,0,https://techcrunch.com/2026/03/10/doge-employe...,20,1,0

In [16]:
df["title_words_count"] = df["title"].str.split().str.len()

In [17]:
df.head()

,title,score,upvote_ratio,num_comments,created_utc,subreddit,is_self,awards,url,post_hour,post_day,is_weekend,title_words_count
0,The Removed DOGE Deposition Videos Have Alread...,55179,0.97,1016,1.773538e+09,technology,False,0,https://www.404media.co/the-removed-doge-depos...,1,6,1,47
1,ChatGPT uninstalls surged by 295% after DoD deal,43096,0.96,1286,1.772496e+09,technology,False,0,https://techcrunch.com/2026/03/02/chatgpt-unin...,0,1,0,8
2,1.5 Million Users Leave ChatGPT,38902,0.96,1525,1.772563e+09,technology,False,0,https://www.forbes.com/sites/barrycollins/2026...,18,1,0,5
3,‘Another internet is possible’: Norway rails a...,35918,0.97,1463,1.773662e+09,technology,False,0,https://www.theguardian.com/world/2026/mar/16/...,11,0,0,8
4,DOGE employee stole Social Security data and p...,35822,0.97,838,1.773174e+09,technology,False,0,https://techcrunch.com/2026/03/10/doge-employe...,20,1,0,15

In [18]:
df["has_question"] = df["title"].str.contains("?" , regex=False).astype(int)

In [19]:
df.head()

,title,score,upvote_ratio,num_comments,created_utc,subreddit,is_self,awards,url,post_hour,post_day,is_weekend,title_words_count,has_question
0,The Removed DOGE Deposition Videos Have Alread...,55179,0.97,1016,1.773538e+09,technology,False,0,https://www.404media.co/the-removed-doge-depos...,1,6,1,47,0
1,ChatGPT uninstalls surged by 295% after DoD deal,43096,0.96,1286,1.772496e+09,technology,False,0,https://techcrunch.com/2026/03/02/chatgpt-unin...,0,1,0,8,0
2,1.5 Million Users Leave ChatGPT,38902,0.96,1525,1.772563e+09,technology,False,0,https://www.forbes.com/sites/barrycollins/2026...,18,1,0,5,0
3,‘Another internet is possible’: Norway rails a...,35918,0.97,1463,1.773662e+09,technology,False,0,https://www.theguardian.com/world/2026/mar/16/...,11,0,0,8,0
4,DOGE employee stole Social Security data and p...,35822,0.97,838,1.773174e+09,technology,False,0,https://techcrunch.com/2026/03/10/doge-employe...,20,1,0,15,0

In [20]:
df["has_number"] = df["title"].str.contains(r"\d").astype(int)

In [21]:
df.head()

,title,score,upvote_ratio,num_comments,created_utc,subreddit,is_self,awards,url,post_hour,post_day,is_weekend,title_words_count,has_question,has_number
0,The Removed DOGE Deposition Videos Have Alread...,55179,0.97,1016,1.773538e+09,technology,False,0,https://www.404media.co/the-removed-doge-depos...,1,6,1,47,0,0
1,ChatGPT uninstalls surged by 295% after DoD deal,43096,0.96,1286,1.772496e+09,technology,False,0,https://techcrunch.com/2026/03/02/chatgpt-unin...,0,1,0,8,0,1
2,1.5 Million Users Leave ChatGPT,38902,0.96,1525,1.772563e+09,technology,False,0,https://www.forbes.com/sites/barrycollins/2026...,18,1,0,5,0,1
3,‘Another internet is possible’: Norway rails a...,35918,0.97,1463,1.773662e+09,technology,False,0,https://www.theguardian.com/world/2026/mar/16/...,11,0,0,8,0,0
4,DOGE employee stole Social Security data and p...,35822,0.97,838,1.773174e+09,technology,False,0,https://techcrunch.com/2026/03/10/doge-employe...,20,1,0,15,0,0

In [39]:
df["controversy_index"] = (1 - df["upvote_ratio"]) * np.log1p(df["num_comments"])

In [40]:
df.head()

,title,score,upvote_ratio,num_comments,created_utc,subreddit,is_self,awards,url,post_hour,post_day,is_weekend,title_words_count,has_question,has_number,controversy_index,sentiment_score,is_extreme_sentiment,viral
0,The Removed DOGE Deposition Videos Have Alread...,55179,0.97,1016,1.773538e+09,technology,0,0,https://www.404media.co/the-removed-doge-depos...,1,6,1,47,0,0,0.207738,0.0258,0,1
1,ChatGPT uninstalls surged by 295% after DoD deal,43096,0.96,1286,1.772496e+09,technology,0,0,https://techcrunch.com/2026/03/02/chatgpt-unin...,0,1,0,8,0,1,0.286403,0.0000,0,1
2,1.5 Million Users Leave ChatGPT,38902,0.96,1525,1.772563e+09,technology,0,0,https://www.forbes.com/sites/barrycollins/2026...,18,1,0,5,0,1,0.293216,-0.0516,0,1
3,‘Another internet is possible’: Norway rails a...,35918,0.97,1463,1.773662e+09,technology,0,0,https://www.theguardian.com/world/2026/mar/16/...,11,0,0,8,0,0,0.218668,0.0000,0,1
4,DOGE employee stole Social Security data and p...,35822,0.97,838,1.773174e+09,technology,0,0,https://techcrunch.com/2026/03/10/doge-employe...,20,1,0,15,0,0,0.201966,0.3400,0,1

In [41]:
import nltk
from nltk.sentiment import SentimentIntensityAnalyzer

In [42]:
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\nitin\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

True

In [43]:
sia = SentimentIntensityAnalyzer()

In [44]:
df["sentiment_score"] = df["title"].apply(
    lambda x: sia.polarity_scores(str(x))["compound"]
)

In [45]:
df.head()

,title,score,upvote_ratio,num_comments,created_utc,subreddit,is_self,awards,url,post_hour,post_day,is_weekend,title_words_count,has_question,has_number,controversy_index,sentiment_score,is_extreme_sentiment,viral
0,The Removed DOGE Deposition Videos Have Alread...,55179,0.97,1016,1.773538e+09,technology,0,0,https://www.404media.co/the-removed-doge-depos...,1,6,1,47,0,0,0.207738,0.0258,0,1
1,ChatGPT uninstalls surged by 295% after DoD deal,43096,0.96,1286,1.772496e+09,technology,0,0,https://techcrunch.com/2026/03/02/chatgpt-unin...,0,1,0,8,0,1,0.286403,0.0000,0,1
2,1.5 Million Users Leave ChatGPT,38902,0.96,1525,1.772563e+09,technology,0,0,https://www.forbes.com/sites/barrycollins/2026...,18,1,0,5,0,1,0.293216,-0.0516,0,1
3,‘Another internet is possible’: Norway rails a...,35918,0.97,1463,1.773662e+09,technology,0,0,https://www.theguardian.com/world/2026/mar/16/...,11,0,0,8,0,0,0.218668,0.0000,0,1
4,DOGE employee stole Social Security data and p...,35822,0.97,838,1.773174e+09,technology,0,0,https://techcrunch.com/2026/03/10/doge-employe...,20,1,0,15,0,0,0.201966,0.3400,0,1

In [46]:
df["is_extreme_sentiment"] = (
    df["sentiment_score"].abs() > 0.5
).astype(int)

In [47]:
df.head()

,title,score,upvote_ratio,num_comments,created_utc,subreddit,is_self,awards,url,post_hour,post_day,is_weekend,title_words_count,has_question,has_number,controversy_index,sentiment_score,is_extreme_sentiment,viral
0,The Removed DOGE Deposition Videos Have Alread...,55179,0.97,1016,1.773538e+09,technology,0,0,https://www.404media.co/the-removed-doge-depos...,1,6,1,47,0,0,0.207738,0.0258,0,1
1,ChatGPT uninstalls surged by 295% after DoD deal,43096,0.96,1286,1.772496e+09,technology,0,0,https://techcrunch.com/2026/03/02/chatgpt-unin...,0,1,0,8,0,1,0.286403,0.0000,0,1
2,1.5 Million Users Leave ChatGPT,38902,0.96,1525,1.772563e+09,technology,0,0,https://www.forbes.com/sites/barrycollins/2026...,18,1,0,5,0,1,0.293216,-0.0516,0,1
3,‘Another internet is possible’: Norway rails a...,35918,0.97,1463,1.773662e+09,technology,0,0,https://www.theguardian.com/world/2026/mar/16/...,11,0,0,8,0,0,0.218668,0.0000,0,1
4,DOGE employee stole Social Security data and p...,35822,0.97,838,1.773174e+09,technology,0,0,https://techcrunch.com/2026/03/10/doge-employe...,20,1,0,15,0,0,0.201966,0.3400,0,1

In [48]:
df["viral"] = df.groupby("subreddit")["score"].transform(
    lambda x: (x >= x.quantile(0.75)).astype(int)
)

In [49]:
df["viral"].value_counts()

viral
0    750
1    250
Name: count, dtype: int64

In [50]:
df.shape

(1000, 19)

In [51]:
df["is_self"] = df["is_self"].astype(int)

In [52]:
df.head()

,title,score,upvote_ratio,num_comments,created_utc,subreddit,is_self,awards,url,post_hour,post_day,is_weekend,title_words_count,has_question,has_number,controversy_index,sentiment_score,is_extreme_sentiment,viral
0,The Removed DOGE Deposition Videos Have Alread...,55179,0.97,1016,1.773538e+09,technology,0,0,https://www.404media.co/the-removed-doge-depos...,1,6,1,47,0,0,0.207738,0.0258,0,1
1,ChatGPT uninstalls surged by 295% after DoD deal,43096,0.96,1286,1.772496e+09,technology,0,0,https://techcrunch.com/2026/03/02/chatgpt-unin...,0,1,0,8,0,1,0.286403,0.0000,0,1
2,1.5 Million Users Leave ChatGPT,38902,0.96,1525,1.772563e+09,technology,0,0,https://www.forbes.com/sites/barrycollins/2026...,18,1,0,5,0,1,0.293216,-0.0516,0,1
3,‘Another internet is possible’: Norway rails a...,35918,0.97,1463,1.773662e+09,technology,0,0,https://www.theguardian.com/world/2026/mar/16/...,11,0,0,8,0,0,0.218668,0.0000,0,1
4,DOGE employee stole Social Security data and p...,35822,0.97,838,1.773174e+09,technology,0,0,https://techcrunch.com/2026/03/10/doge-employe...,20,1,0,15,0,0,0.201966,0.3400,0,1

In [53]:
df.to_csv("reddit_features.csv", index=False)